name: Docker

on:
  schedule:
    - cron: "0 6 * * 1"   # Every Monday at 06:00 UTC
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    # runs-on: ubuntu-24.04
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout remote repo & branch
        uses: actions/checkout@v4
        with:
          repository: sever-sever/vyos-build
          ref: T8065
          fetch-depth: 1

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/arm64
          push: true
          # tags: ghcr.io/${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Get repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      # Do not work for ARM
      # - name: Delete old images
      #   uses: snok/container-retention-policy@v3.0.0
      #   with:
      #     image-names: ${{ env.REPOSITORY_NAME }}
      #     cut-off: 2w 3d
      #     keep-n-most-recent: 1
      #     account: user
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.REPOSITORY_NAME }}
          package-type: container
          min-versions-to-keep: 3
